# I tried challenged Kaggle with my power!

# Self‐introduction

- Name: Nakanishi Tetsuhiro
- Job：Engineers close to data scientists
- I Love...

    - Vim
    - Ubuntu
    - Music（Karaoke、Electric Guitar）

## Today's think

- そろそろAppleがヤバそうなのでDellのLaptopにUbuntu入れたのをメインマシンにしたい



# Attention!

- このLTはわたくし中西が１ヶ月間頑張った進捗報告です
- さまざまな間違いが含まれている可能性があります（ツッコミお待ちしております！）

# 今回挑戦するCompetition

![title](img/Competition_top.png)


Titanic号に乗っていた乗客の生存を予測するようです

# ＼それmeetup001でやったで／

In [1]:
!cowsay "Really!?"

 __________ 
< Really!? >
 ---------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


In [5]:
!cowsay -f bong "OEEEEEEEEEEEE"  && echo "" && echo-sd "Vomiting due to tension"

 _______________ 
< OEEEEEEEEEEEE >
 --------------- 
         \
          \
            ^__^ 
    _______/(oo)
/\/(       /(__)
   | W----|| |~|
   ||     || |~|  ~~
             |~|  ~
             |_| o
             |#|/
            _+#+_

＿人人人人人人人人人人人人人＿
＞　Vomiting due to tension　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^￣


## やり始めてから気づいたので許してください
## (´；ω；｀)

# とりあえずCompetitionのページ見てみた

---

# HOME

> If you're new to data science and machine learning, or looking for a simple intro to the Kaggle competitions platform, this is the best place to start. Continue reading below the competition description to discover a number of tutorials, benchmark models, and more.

### ほう。俺にぴったりなCompetition見つけた！(๑•̀ㅂ•́)و✧

<style>

.center{
	text-align: center
}

</style>


# Data (A lot...)

- train.csv (59.76 kb)
- test.csv (27.96 kb)
- gendermodel.csv (3.18 kb)
- genderclassmodel.csv (3.18 kb)
- gendermodel.py (3.58 kb)
- genderclassmodel.py (5.63 kb)
- myfirstforest.py (3.99 kb)

ひとまず今回は train.csv と test.csv のみを用いて生存者の予測モデルを作成

## Meetup015のnotebookを参考に実際に作業してみた

## Preparation

In [4]:
# Load essential modules
import numpy as np
import pandas as pd
from sklearn import tree

# Basic drawing library
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Display figure in ipython notebook
%matplotlib inline

# Show all columns with pandas
pd.options.display.max_columns = None

## Loading data

In [6]:
df_train = pd.read_csv("data/train.csv")
df_test = pd.read_csv("data/test.csv")

## 学習用データの中身を確認

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB


## 学習用データの整形

機械学習が理解できる形（数値データ）に整形する

例）Male   → 0  
　　Female → 1

## Sexの変換(Male: 0, Female: 1)

In [8]:
df_train["Sex"].head(10)

0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: Sex, dtype: object

ここで俺氏、文字データから数値データへの変換方法を忘れる  

→Meetup15の資料見返し

mapの引数でDict渡すとそれだけで文字データから数値データに変換してくれるの？

### 実際にやってみた

In [9]:
Sex_typeId = {'male': 0, 'female': 1}

In [10]:
df_train["SexId"] = df_train['Sex'].map(Sex_typeId)
# .mapを用いてSexを0と1のデータに変換
# なんかSexカラムにそのまま上書きしたら怒られたのでSexIdカラムを新しく作成してそこに変換データを入れる

In [11]:
df_train["SexId"].head(10)
# データの確認

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: SexId, dtype: int64

In [7]:
!cowsay -f bong "OEEEEEEEEEE"  && echo "" && echo-sd ".map() SUGEEEEEEEEEEEEEEEEEEEEEEEE"

 _____________ 
< OEEEEEEEEEE >
 ------------- 
         \
          \
            ^__^ 
    _______/(oo)
/\/(       /(__)
   | W----|| |~|
   ||     || |~|  ~~
             |~|  ~
             |_| o
             |#|/
            _+#+_

＿人人人人人人人人人人人人人人人人人人人＿
＞　.map() SUGEEEEEEEEEEEEEEEEEEEEEEEE　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^￣



## Embarkedの変換 (S: 0, C: 1, Q: 2)

In [13]:
# 変換のまえにNaN値を埋めよう

# Int64Index: 891
# Embarked       889

df_train["Embarked"] = df_train["Embarked"].fillna("S")
# NaN値のところはfillnaメソッドを使ってSで埋める

In [14]:
Embarked_typeId = {'S': 0, 'C': 1, 'Q': 2}

In [15]:
df_train["EmbarkedId"] = df_train['Embarked'].map(Embarked_typeId)

In [16]:
df_train["EmbarkedId"].head(10)
# データの確認

0    0
1    1
2    0
3    0
4    0
5    2
6    0
7    0
8    0
9    1
Name: EmbarkedId, dtype: int64

## AgeのNaN値を平均値で埋める

In [17]:
df_train["Age"] = df_train["Age"].fillna(df_train["Age"].mean())

## FareのNaN値を平均値で埋める

In [18]:
df_train["Fare"] = df_train["Fare"].fillna(df_train["Fare"].mean())

## データ整形おわり

## 学習用の説明変数と目的変数を指定

## 目的変数 (Survived)

In [19]:
target = df_train["Survived"].values

## 説明変数 (SexId, Age, Pclass, Fare, EmbarkedId)

In [20]:
features_one = df_train[["SexId", "Age", "Pclass", "Fare", "EmbarkedId"]].values
# 使う変数をデータフレームの中からカラム名で指定してfeatures_oneに突っ込む

## scikit-learnで学習させる

### 今回は決定木を利用した分類器作成に挑戦

In [21]:
my_tree_one = tree.DecisionTreeClassifier()
# DecisionTreeClassifierを初期化

In [22]:
my_tree_one = my_tree_one.fit(features_one, target)
# 説明変数と目的変数をnumpy.arrayでDecisionTreeClassifierに投げる
# 質問：my_tree_one.fit(X,Y)これってやっぱり説明変数がＸで目的変数がＹ？逆じゃだめ？

In [23]:
my_tree_one.feature_importances_
# それぞれの変数が与える影響度？を確認

array([ 0.31117584,  0.24409711,  0.12861331,  0.2993524 ,  0.01676135])

In [24]:
my_tree_one.score(features_one, target)
# 正答率をサクッと確認

0.97979797979797978

- 正答率97%!!
- オーバーフィッティングとかしてそうだけど今回はこのままいきます

## テストデータのSurvivedを予測してみる

## テストデータの変換作業をまだしてなかった。。

In [25]:
df_test.info()
# テストデータの確認

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 39.2+ KB


In [26]:
df_test["SexId"] = df_test['Sex'].map(Sex_typeId)
### .mapを用いてtestデータのSexを0と1のデータに変換(先程作成したSex_typeIdを利用)

In [27]:
df_test["SexId"].head(10)
# データの確認

0    0
1    1
2    0
3    0
4    1
5    0
6    1
7    0
8    1
9    0
Name: SexId, dtype: int64

In [28]:
df_test["Embarked"] = df_test["Embarked"].fillna("S")
# NaN値のところはfillnaメソッドを使ってSで埋める

In [29]:
df_test["EmbarkedId"] = df_test['Embarked'].map(Embarked_typeId)
### .mapを用いてtestデータのEmbarkedを0と1のデータに変換(先程作成したEmbarked_typeIdを利用)

In [30]:
df_test["Age"] = df_test["Age"].fillna(df_test["Age"].mean())
# NaN値を平均値で埋める

In [31]:
df_test["Fare"] = df_test["Fare"].fillna(df_test["Fare"].mean())
# NaN値を平均値で埋める

In [32]:
# データの確認
df_test[["SexId", "Age", "Pclass", "Fare", "EmbarkedId"]].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 5 columns):
SexId         418 non-null int64
Age           418 non-null float64
Pclass        418 non-null int64
Fare          418 non-null float64
EmbarkedId    418 non-null int64
dtypes: float64(2), int64(3)
memory usage: 19.6 KB


## テストデータの変換作業終わり

## 先程学習させたモデル(my_tree_one)を使って、testデータのSurvivedの予測をしてみる

In [39]:
test_features = df_test[["SexId", "Age", "Pclass", "Fare", "EmbarkedId"]].values
test_features
# scikit-learnで使えるようにPandasのデータフレーム(df_test)をnumpy_arrayの形に変換

array([[  0.        ,  34.5       ,   3.        ,   7.8292    ,   2.        ],
       [  1.        ,  47.        ,   3.        ,   7.        ,   0.        ],
       [  0.        ,  62.        ,   2.        ,   9.6875    ,   2.        ],
       ..., 
       [  0.        ,  38.5       ,   3.        ,   7.25      ,   0.        ],
       [  0.        ,  30.27259036,   3.        ,   8.05      ,   0.        ],
       [  0.        ,  30.27259036,   3.        ,  22.3583    ,   1.        ]])

In [34]:
my_prediction = my_tree_one.predict(test_features)
my_prediction
# .predict()でSurvivedの値を予測

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

# 予測できた！やった！(๑•̀ㅂ•́)و✧

# 提出用データ(csvファイル)の作成

In [35]:
PassengerId =np.array(df_test["PassengerId"]).astype(int)
# Pandasのデータフレームをnumpy_arrayの形に変換

my_solution = pd.DataFrame(my_prediction, PassengerId, columns = ["Survived"])
# PassengerId(indexに指定)とSurvivedの２つのカラムを持ったPandasのDataFrameを作成

# class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
# http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [36]:
print(my_solution.shape)
# データ数が418あるか確認

(418, 1)


In [37]:
my_solution.head()
# 提出するcsvデータの形式があってるか確認

Survived
892         0
893         0
894         1
895         1
896         1

In [38]:
my_solution.to_csv("output/submission03.csv", index_label = ["PassengerId"])
# 提出するデータを出力

## submission03.csvをKaggleのページに提出

![title](img/Submission03_rank.png)

# 5817チーム中2966位！！！！！

## 今後の課題

- モデルデータがオーバーフィッティングしてるとかしてないとかどうやって調べるんだろう？
- 他のカラムのデータもまとめて突っ込んだら精度あがる？
- 他のアルゴリズムの方が精度上がる？

# 今回は以上(๑•̀ㅂ•́)و✧

# By the way...

### こちらのスライドはみんな大好きJupyter notebookで作成されています

# notebookをスライドにする手順

1. 発表用のnotebookを頑張って作成する
2. Terminal で下記のコマンドを実行するとhoge.slides.htmlが作成される

    $ jupyter nbconvert hoge.ipynb --to slides --post serve  
   
3. 直後に自動的にブラウザが立ち上がるので早速LTをしましょう(๑•̀ㅂ•́)و✧





# 作成したスライドをWebで共有する手順

1. 上記のコマンドでhoge.slides.htmlを作業ディレクトリに出力しておく
2. githubにディレクトリをpushする
2. http://nbviewer.jupyter.org/ でgithubでpushした.ipynbファイルのURLを貼り付けて送信
3. 表示されたページの右上にあるプレゼントみたいなボタンをクリック！

## Good!

- Jupyternotebookで作業した内容をそのまま発表できるか作業手順を詳しく発表するときは楽
- Githubでコードを共有 = スライドを共有


## Bad...

- 変換しないとスライドが確認できない
- デザインの融通が効かない
- 単純に楽に発表用資料作りたいならMarkdownで資料作成できるMarpの方がよさそう（リアルタイムでプレビューできるし。。。）

# Thank you for listening (๑•̀ㅂ•́)و✧