# I tried challenged Kaggle with my power!

# Self‐introduction

- Name: Nakanishi Tetsuhiro
- Job：Engineers close to data scientists
- I Love...

    - Vim
    - Ubuntu
    - Music（Karaoke、Electric Guitar）

## Today's think

- I want to Dell's Laptop the main machine. OS in Ubuntu!



# Attention!

- This LT is a progress report that I worked hard for one month
- There may be various mistakes included（I am waiting for TSUKKOMI！）

# Competition to challenge this time

![title](img/Competition_top.png)


We anticipate the survival of passengers aboard Titanic.
(Titanic号に乗っていた乗客の生存を予測するようです)

# ＼Oh... We tried this competition when meetup001／

In [11]:
!cowsay "Really!?"

 __________
< Really!? >
 ----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


In [12]:
!cowsay -f bong "OEEEEEEEEEEEE"  && echo "" && echo-sd "Vomiting due to tension!!"

 _______________
< OEEEEEEEEEEEE >
 ---------------
         \
          \
            ^__^ 
    _______/(oo)
/\/(       /(__)
   | W----|| |~|
   ||     || |~|  ~~
             |~|  ~
             |_| o
             |#|/
            _+#+_

＿人人人人人人人人人人人人人人＿
＞　Vomiting due to tension!!　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^￣


## Please forgive me! I noticed it since I started doing it...
## (´；ω；｀)

# I looked at the page of Competition

---

# HOME

> If you're new to data science and machine learning, or looking for a simple intro to the Kaggle competitions platform, this is the best place to start.

### Yes! I found Competition that is right for me! (๑•̀ㅂ•́)و✧

<style>

.center{
	text-align: center
}

</style>


# Data (A lot...)

- train.csv (59.76 kb)
- test.csv (27.96 kb)
- gendermodel.csv (3.18 kb)
- genderclassmodel.csv (3.18 kb)
- gendermodel.py (3.58 kb)
- genderclassmodel.py (5.63 kb)
- myfirstforest.py (3.99 kb)

For now, I use train.csv and test.csv only.

## I actually tried working with reference to the notebook of Meetup015

## Preparation

In [13]:
# Load essential modules
import numpy as np
import pandas as pd
from sklearn import tree

# Basic drawing library
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
# Display figure in ipython notebook
%matplotlib inline

# Show all columns with pandas
pd.options.display.max_columns = None

## Loading data

In [15]:
df_train = pd.read_csv("data/train.csv")
df_test = pd.read_csv("data/test.csv")

## Checked training data

In [16]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


## Convert training data

machine learning (Strings data to numerical data)

Ex）Male   → 0  
　　Female → 1

## Convert Sex(Male: 0, Female: 1)

In [17]:
df_train["Sex"].head(10)

0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: Sex, dtype: object

Now, I forget how to convert character data to numerical data

→ Looking back on the notebook from Meetup 15

In [18]:
Sex_typeId = {'male': 0, 'female': 1}

In [19]:
df_train["SexId"] = df_train['Sex'].map(Sex_typeId)
# Use .map(), Convert to Numerical data
# なんかSexカラムにそのまま上書きしたら怒られたのでSexIdカラムを新しく作成してそこに変換データを入れる

In [20]:
df_train["SexId"].head(10)
# Checked data

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: SexId, dtype: int64

In [21]:
!cowsay -f bong "OEEEEEEEEEE"  && echo "" && echo-sd ".map() SUGEEEEEEEEEEEEEEEEEEEEEEEE"

 _____________
< OEEEEEEEEEE >
 -------------
         \
          \
            ^__^ 
    _______/(oo)
/\/(       /(__)
   | W----|| |~|
   ||     || |~|  ~~
             |~|  ~
             |_| o
             |#|/
            _+#+_

＿人人人人人人人人人人人人人人人人人人人＿
＞　.map() SUGEEEEEEEEEEEEEEEEEEEEEEEE　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^￣



## Convert Embarked (S: 0, C: 1, Q: 2)

In [22]:
# Fill NaN value before convert

# Index: 891
# Embarked: 889

df_train["Embarked"] = df_train["Embarked"].fillna("S")
# NaN値のところはfillnaメソッドを使ってSで埋める

In [23]:
Embarked_typeId = {'S': 0, 'C': 1, 'Q': 2}

In [24]:
df_train["EmbarkedId"] = df_train['Embarked'].map(Embarked_typeId)

In [25]:
df_train["EmbarkedId"].head(10)
# Checked data

0    0
1    1
2    0
3    0
4    0
5    2
6    0
7    0
8    0
9    1
Name: EmbarkedId, dtype: int64

## Fill the NaN value of Age with the average value

In [26]:
df_train["Age"] = df_train["Age"].fillna(df_train["Age"].mean())

## Fill NaN value of Fare with average value

In [27]:
df_train["Fare"] = df_train["Fare"].fillna(df_train["Fare"].mean())

## Finish the conversion

## 学習用の説明変数と目的変数を指定

## Response variable (Survived)

In [28]:
target = df_train["Survived"].values

## Explanatory variable(SexId, Age, Pclass, Fare, EmbarkedId)

In [29]:
features_one = df_train[["SexId", "Age", "Pclass", "Fare", "EmbarkedId"]].values
# 使う変数をデータフレームの中からカラム名で指定してfeatures_oneに突っ込む

## Learninig with scikit-learn

### In this time I try to create classifiers using decision trees

In [30]:
my_tree_one = tree.DecisionTreeClassifier()
# Initialising DecisionTreeClassifier

In [31]:
my_tree_one = my_tree_one.fit(features_one, target)
# 説明変数と目的変数をnumpy.arrayでDecisionTreeClassifierに投げる
# 質問：my_tree_one.fit(X,Y)これってやっぱり説明変数がＸで目的変数がＹ？逆じゃだめ？

In [32]:
my_tree_one.feature_importances_
# それぞれの変数が与える影響度？を確認

array([ 0.31117584,  0.25663428,  0.12561225,  0.28548142,  0.02109621])

In [33]:
my_tree_one.score(features_one, target)
# 正答率をサクッと確認

0.97979797979797978

- 正答率97%!!
- オーバーフィッティングとかしてそうだけど今回はこのままいきます

## テストデータのSurvivedを予測してみる

## Oops... Not finished Convert test-data

In [34]:
df_test.info()
# Checked test-data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [35]:
df_test["SexId"] = df_test['Sex'].map(Sex_typeId)
### .mapを用いてtestデータのSexを0と1のデータに変換(先程作成したSex_typeIdを利用)

In [36]:
df_test["SexId"].head(10)
# Checked data

0    0
1    1
2    0
3    0
4    1
5    0
6    1
7    0
8    1
9    0
Name: SexId, dtype: int64

In [37]:
df_test["Embarked"] = df_test["Embarked"].fillna("S")
# NaN値のところはfillnaメソッドを使ってSで埋める

In [38]:
df_test["EmbarkedId"] = df_test['Embarked'].map(Embarked_typeId)
### .mapを用いてtestデータのEmbarkedを0と1のデータに変換(先程作成したEmbarked_typeIdを利用)

In [39]:
df_test["Age"] = df_test["Age"].fillna(df_test["Age"].mean())
# NaN値を平均値で埋める

In [40]:
df_test["Fare"] = df_test["Fare"].fillna(df_test["Fare"].mean())
# NaN値を平均値で埋める

In [48]:
# Checked data
df_test[["SexId", "Age", "Pclass", "Fare", "EmbarkedId"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 5 columns):
SexId         418 non-null int64
Age           418 non-null float64
Pclass        418 non-null int64
Fare          418 non-null float64
EmbarkedId    418 non-null int64
dtypes: float64(2), int64(3)
memory usage: 16.4 KB


## Finished Convert test-data

## 先程学習させたモデル(my_tree_one)を使って、testデータのSurvivedの予測をしてみる

In [42]:
test_features = df_test[["SexId", "Age", "Pclass", "Fare", "EmbarkedId"]].values
test_features
# scikit-learnで使えるようにPandasのデータフレーム(df_test)をnumpy_arrayの形に変換

array([[  0.        ,  34.5       ,   3.        ,   7.8292    ,   2.        ],
       [  1.        ,  47.        ,   3.        ,   7.        ,   0.        ],
       [  0.        ,  62.        ,   2.        ,   9.6875    ,   2.        ],
       ..., 
       [  0.        ,  38.5       ,   3.        ,   7.25      ,   0.        ],
       [  0.        ,  30.27259036,   3.        ,   8.05      ,   0.        ],
       [  0.        ,  30.27259036,   3.        ,  22.3583    ,   1.        ]])

In [43]:
my_prediction = my_tree_one.predict(test_features)
my_prediction
# .predict()でSurvivedの値を予測

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

# Yeah! It was Predict(๑•̀ㅂ•́)و✧

# Export Submission data (.csv file) 

In [44]:
PassengerId =np.array(df_test["PassengerId"]).astype(int)
# Pandasのデータフレームをnumpy_arrayの形に変換

my_solution = pd.DataFrame(my_prediction, PassengerId, columns = ["Survived"])
# PassengerId(indexに指定)とSurvivedの２つのカラムを持ったPandasのDataFrameを作成

# class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
# http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

In [45]:
print(my_solution.shape)
# データ数が418あるか確認

(418, 1)


In [46]:
my_solution.head()
# 提出するcsvデータの形式があってるか確認

Survived
892         0
893         0
894         1
895         1
896         1

In [47]:
my_solution.to_csv("output/submission03.csv", index_label = ["PassengerId"])
# Export submission data

## Make a Submission

![title](img/Submission03_rank.png)

# 2966th out of 5817 !!!

## Future tasks

- モデルデータがオーバーフィッティングしてるとかしてないとかどうやって調べるんだろう？
- 他のカラムのデータもまとめて突っ込んだら精度あがる？
- 他のアルゴリズムの方が精度上がる？

# THE END(๑•̀ㅂ•́)و✧

# By the way...

### This slide is created with Jupyter notebook

# notebookをスライドにする手順

1. 発表用のnotebookを頑張って作成する
2. Terminal で下記のコマンドを実行するとhoge.slides.htmlが作成される

    $ jupyter nbconvert hoge.ipynb --to slides --post serve  
   
3. 直後に自動的にブラウザが立ち上がるので早速LTをしましょう(๑•̀ㅂ•́)و✧





# 作成したスライドをWebで共有する手順

1. 上記のコマンドでhoge.slides.htmlを作業ディレクトリに出力しておく
2. githubにディレクトリをpushする
2. http://nbviewer.jupyter.org/ でgithubでpushした.ipynbファイルのURLを貼り付けて送信
3. 表示されたページの右上にあるプレゼントみたいなボタンをクリック！

## Good!

- Jupyternotebookで作業した内容をそのまま発表できるか作業手順を詳しく発表するときは楽
- Githubでコードを共有 = スライドを共有


## Bad...

- 変換しないとスライドが確認できない
- デザインの融通が効かない
- 単純に楽に発表用資料作りたいならMarkdownで資料作成できるMarpの方がよさそう（リアルタイムでプレビューできるし。。。）

# Thank you for listening (๑•̀ㅂ•́)و✧